<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Confuser.Protections</RootNamespace>
    <AssemblyName>Confuser.Protections</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\ConfuserEx.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Confuser.Core\Confuser.Core.csproj" />
    <ProjectReference Include="..\Confuser.DynCipher\Confuser.DynCipher.csproj" />
    <ProjectReference Include="..\Confuser.Renamer\Confuser.Renamer.csproj" />
    <ProjectReference Include="..\Confuser.Runtime\Confuser.Runtime.csproj" />
  </ItemGroup>
</Project>
