<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Confuser.CLI</RootNamespace>
    <AssemblyName>Confuser.CLI</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\ConfuserEx.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
    <ProjectReference Include="..\Confuser.Core\Confuser.Core.csproj" />
    <ProjectReference Include="..\Confuser.DynCipher\Confuser.DynCipher.csproj" />
    <ProjectReference Include="..\Confuser.Protections\Confuser.Protections.csproj" />
    <ProjectReference Include="..\Confuser.Renamer\Confuser.Renamer.csproj" />
    <ProjectReference Include="..\Confuser.Runtime\Confuser.Runtime.csproj" />
  </ItemGroup>
</Project>
