<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>ConfuserEx</RootNamespace>
    <AssemblyName>ConfuserEx</AssemblyName>
    <ApplicationIcon>ConfuserEx.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\ConfuserEx.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Confuser.Core\Confuser.Core.csproj" />
    <ProjectReference Include="..\Confuser.DynCipher\Confuser.DynCipher.csproj" />
    <ProjectReference Include="..\Confuser.Protections\Confuser.Protections.csproj" />
    <ProjectReference Include="..\Confuser.Renamer\Confuser.Renamer.csproj" />
    <ProjectReference Include="..\Confuser.Runtime\Confuser.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ConfuserEx.ico" />
    <Resource Include="Resources\*.png" />
    <Resource Include="Resources\FontAwesome.otf" />
  </ItemGroup>
</Project>
