<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net8.0</TargetFrameworks>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <RootNamespace>ConfuserEx.Corpus.ExceptionFlow</RootNamespace>
    <AssemblyName>ExceptionFlow</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>
